name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List directory structure
        run: ls -R

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sgarmendia/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true sgarmendia/react-test npm run test
 
      - run: docker build -t sgarmendia/docker-react .
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-1-887236268408
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip